export const ADD_QUESTION = 'ADD_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
// Comment types
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_FULFILLED = "ADD_COMMENT_FULFILLED"
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_FULFILLED = "FETCH_COMMENTS_FULFILLED"
export const REPLY_TO_COMMENT = 'REPLY_TO_COMMENT';
export const REPLY_TO_COMMENT_FULFILLED = 'REPLY_TO_COMMENT_FULFILLED';
