// Question types
export const ADD_QUESTION = 'ADD_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const REORDER_QUESTION = 'REORDER_QUESTION';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_QUESTIONS_FULFILLED = 'FETCH_QUESTIONS_FULFILLED';
export const FETCH_QUESTION = 'FETCH_QUESTION';
export const FETCH_QUESTION_FULFILLED = 'FETCH_QUESTION_FULFILLED';
export const FETCH_QUESTION_USAGE = 'FETCH_QUESTION_USAGE';
export const FETCH_QUESTION_USAGE_FULFILLED = 'FETCH_QUESTION_USAGE_FULFILLED';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const DELETE_QUESTION_FULFILLED = 'DELETE_QUESTION_FULFILLED';
export const PUBLISH_QUESTION = 'PUBLISH_QUESTION';
export const PUBLISH_QUESTION_FULFILLED = 'PUBLISH_QUESTION_FULFILLED';
export const SAVE_QUESTION = 'SAVE_QUESTION';
export const SAVE_QUESTION_FULFILLED = 'SAVE_QUESTION_FULFILLED';
export const SAVE_DRAFT_QUESTION = 'SAVE_DRAFT_QUESTION';
export const SAVE_DRAFT_QUESTION_FULFILLED = 'SAVE_DRAFT_QUESTION_FULFILLED';

// Comment types
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_FULFILLED = 'ADD_COMMENT_FULFILLED';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_FULFILLED = 'FETCH_COMMENTS_FULFILLED';

// Tutorial Info
export const SET_STEPS = 'SET_STEPS';

// Landing types
export const FETCH_STATS = 'FETCH_STATS';
export const FETCH_STATS_FULFILLED = 'FETCH_STATS_FULFILLED';
export const SET_STATS = 'SET_STATS';
export const SET_STATS_FULFILLED = 'SET_STATS_FULFILLED';

// Search types
export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const FETCH_SEARCH_RESULTS_FULFILLED = 'FETCH_SEARCH_RESULTS_FULFILLED';
export const FETCH_MORE_SEARCH_RESULTS = 'FETCH_MORE_SEARCH_RESULTS';
export const FETCH_MORE_SEARCH_RESULTS_FULFILLED = 'FETCH_MORE_SEARCH_RESULTS_FULFILLED';
export const FETCH_LAST_SEARCH = 'FETCH_LAST_SEARCH';
export const FETCH_LAST_SEARCH_FULFILLED = 'FETCH_LAST_SEARCH_FULFILLED';
export const SET_LAST_SEARCH = 'SET_LAST_SEARCH';

// Notifications
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_FULFILLED = 'FETCH_NOTIFICATIONS_FULFILLED';
export const READ_NOTIFICATIONS = 'READ_NOTIFICATIONS';
export const READ_NOTIFICATIONS_FULFILLED = 'READ_NOTIFICATIONS_FULFILLED';

// Response Set types
export const FETCH_RESPONSE_SETS = 'FETCH_RESPONSE_SETS';
export const FETCH_RESPONSE_SETS_FULFILLED = 'FETCH_RESPONSE_SETS_FULFILLED';
export const FETCH_RESPONSE_SET = 'FETCH_RESPONSE_SET';
export const FETCH_RESPONSE_SET_FULFILLED = 'FETCH_RESPONSE_SET_FULFILLED';
export const FETCH_RESPONSE_SET_USAGE = 'FETCH_RESPONSE_SET_USAGE';
export const FETCH_RESPONSE_SET_USAGE_FULFILLED = 'FETCH_RESPONSE_SET_USAGE_FULFILLED';
export const SAVE_RESPONSE_SET = 'SAVE_RESPONSE_SET';
export const SAVE_RESPONSE_SET_FULFILLED = 'SAVE_RESPONSE_SET_FULFILLED';
export const SAVE_DRAFT_RESPONSE_SET = 'SAVE_DRAFT_RESPONSE_SET';
export const SAVE_DRAFT_RESPONSE_SET_FULFILLED = 'SAVE_DRAFT_RESPONSE_SET_FULFILLED';
export const PUBLISH_RESPONSE_SET = 'PUBLISH_RESPONSE_SET';
export const PUBLISH_RESPONSE_SET_FULFILLED = 'PUBLISH_RESPONSE_SET_FULFILLED';
export const DELETE_RESPONSE_SET = 'DELETE_RESPONSE_SET';
export const DELETE_RESPONSE_SET_FULFILLED = 'DELETE_RESPONSE_SET_FULFILLED';

// Current user types
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_FULFILLED = 'FETCH_CURRENT_USER_FULFILLED';
export const LOG_IN = 'LOG_IN';
export const LOG_IN_FULFILLED = 'LOG_IN_FULFILLED';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_FULFILLED = 'SIGN_UP_FULFILLED';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED';

// Form types
export const FETCH_FORMS = 'FETCH_FORMS';
export const FETCH_FORMS_FULFILLED = 'FETCH_FORMS_FULFILLED';
export const FETCH_FORM = 'FETCH_FORM';
export const FETCH_FORM_FULFILLED = 'FETCH_FORM_FULFILLED';
export const PUBLISH_FORM = 'PUBLISH_FORM';
export const PUBLISH_FORM_FULFILLED = 'PUBLISH_FORM_FULFILLED';
export const SAVE_FORM = 'SAVE_FORM';
export const SAVE_FORM_FULFILLED = 'SAVE_FORM_FULFILLED';
export const SAVE_DRAFT_FORM = 'SAVE_DRAFT_FORM';
export const SAVE_DRAFT_FORM_FULFILLED = 'SAVE_DRAFT_FORM_FULFILLED';
export const CREATE_FORM = 'CREATE_FORM';
export const ADD_FORM = 'ADD_FORM';
export const REMOVE_FORM = 'REMOVE_FORM';
export const REORDER_FORM = 'REORDER_FORM';
export const DELETE_FORM = 'DELETE_FORM';
export const DELETE_FORM_FULFILLED = 'DELETE_FORM_FULFILLED';

// Question Types
export const FETCH_QUESTION_TYPE = 'FETCH_QUESTION_TYPE';
export const FETCH_QUESTION_TYPE_FULFILLED = 'FETCH_QUESTION_TYPE_FULFILLED';
export const FETCH_QUESTION_TYPES = 'FETCH_QUESTION_TYPES';
export const FETCH_QUESTION_TYPES_FULFILLED = 'FETCH_QUESTION_TYPES_FULFILLED';

// Response Types
export const FETCH_RESPONSE_TYPE = 'FETCH_RESPONSE_TYPE';
export const FETCH_RESPONSE_TYPE_FULFILLED = 'FETCH_RESPONSE_TYPE_FULFILLED';
export const FETCH_RESPONSE_TYPES = 'FETCH_RESPONSE_TYPES';
export const FETCH_RESPONSE_TYPES_FULFILLED = 'FETCH_RESPONSE_TYPES_FULFILLED';

// Concepts
export const FETCH_CONCEPTS = 'FETCH_CONCEPTS';
export const FETCH_CONCEPTS_FULFILLED = 'FETCH_CONCEPTS_FULFILLED';
export const FETCH_CONCEPTS_REJECTED  = 'FETCH_CONCEPTS_REJECTED';
export const FETCH_CONCEPT_SYSTEMS = 'FETCH_CONCEPT_SYSTEMS';
export const FETCH_CONCEPT_SYSTEMS_FULFILLED = 'FETCH_CONCEPT_SYSTEMS_FULFILLED';
export const FETCH_CONCEPT_SYSTEMS_REJECTED  = 'FETCH_CONCEPT_SYSTEMS_REJECTED';

// Surveillance System Types
export const FETCH_SURVEILLANCE_SYSTEMS = 'FETCH_SURVEILLANCE_SYSTEMS';
export const FETCH_SURVEILLANCE_SYSTEMS_FULFILLED = 'FETCH_SURVEILLANCE_SYSTEMS_FULFILLED';

// Surveillance Program Types
export const FETCH_SURVEILLANCE_PROGRAMS = 'FETCH_SURVEILLANCE_PROGRAMS';
export const FETCH_SURVEILLANCE_PROGRAMS_FULFILLED = 'FETCH_SURVEILLANCE_PROGRAMS_FULFILLED';

// Survey types
export const FETCH_SURVEYS = 'FETCH_SURVEYS';
export const FETCH_SURVEYS_FULFILLED = 'FETCH_SURVEYS_FULFILLED';
export const FETCH_SURVEY = 'FETCH_SURVEY';
export const FETCH_SURVEY_FULFILLED = 'FETCH_SURVEY_FULFILLED';
export const PUBLISH_SURVEY = 'PUBLISH_SURVEY';
export const PUBLISH_SURVEY_FULFILLED = 'PUBLISH_SURVEY_FULFILLED';
export const SAVE_SURVEY = 'SAVE_SURVEY';
export const SAVE_SURVEY_FULFILLED = 'SAVE_SURVEY_FULFILLED';
export const SAVE_DRAFT_SURVEY = 'SAVE_DRAFT_SURVEY';
export const SAVE_DRAFT_SURVEY_FULFILLED = 'SAVE_DRAFT_SURVEY_FULFILLED';
export const CREATE_SURVEY = 'CREATE_SURVEY';
export const DELETE_SURVEY = 'DELETE_SURVEY';
export const DELETE_SURVEY_FULFILLED = 'DELETE_SURVEY_FULFILLED';

// Current User
export const LOG_OUT = 'LOG_OUT';

// Publisher types
export const FETCH_PUBLISHERS = 'FETCH_PUBLISHERS';
export const FETCH_PUBLISHERS_FULFILLED = 'FETCH_PUBLISHERS_FULFILLED';

// Middleware
export const FETCH_QUESTIONS_FROM_MIDDLE = 'FETCH_QUESTIONS_FROM_MIDDLE';
export const FETCH_QUESTIONS_FROM_MIDDLE_FULFILLED = 'FETCH_QUESTIONS_FROM_MIDDLE_FULFILLED';
export const FETCH_QUESTION_FROM_MIDDLE = 'FETCH_QUESTION_FROM_MIDDLE';
export const FETCH_QUESTION_FROM_MIDDLE_FULFILLED = 'FETCH_QUESTION_FROM_MIDDLE_FULFILLED';
export const FETCH_RESPONSE_SET_FROM_MIDDLE = 'FETCH_RESPONSE_SET_FROM_MIDDLE';
export const FETCH_RESPONSE_SET_FROM_MIDDLE_FULFILLED = 'FETCH_RESPONSE_SET_FROM_MIDDLE_FULFILLED';
export const FETCH_FORMS_FROM_MIDDLE = 'FETCH_FORMS_FROM_MIDDLE';
export const FETCH_FORMS_FROM_MIDDLE_FULFILLED = 'FETCH_FORMS_FROM_MIDDLE_FULFILLED';
export const FETCH_FORM_FROM_MIDDLE = 'FETCH_FORM_FROM_MIDDLE';
export const FETCH_FORM_FROM_MIDDLE_FULFILLED = 'FETCH_FORM_FROM_MIDDLE_FULFILLED';
